### ISSUE TITLE
[DOCS] Set up draft documentations

### ISSUE THREAD

**Issue by nickkies** [mobi-projects/nail-case-server#1]
# Set up draft documentations

## TODO

- [ ] README 초안
- [ ] MIT lisense 작성
- [ ] Issue, PR template 작성
- [ ] WIKI와 기본적인 파일 구조 생성(추후에 작성돼야 하는 것은 임시 파일로)
- [ ] Contribution 관련 규칙 초안
