### ISSUE TITLE
[Feat] 프로젝트 초기 생성 및 구성

### ISSUE THREAD

**Issue by dongminjang24** [mobi-projects/nail-case-server#3]
# Set up project config

## TODO

- [x] 초기환경 세팅
  - [x] 'build.gradle' 설정
  - [x] 베이스 라이브러리 추가
 
- [x] Config 설정
  - [x] swagger config
  - [x] message config

- [x] 데이터 베이스 설정 
  - [x] H2 설정추가
  - [x] PostgreSQL 설정추가
  
- [x] 보안설정
  - [x]  Spring Security 추가
  - [x]  기본 인증 및 권한 설정

- [x] 문서화
  - [x] API 문서화 도구 설정 (Swagger, Spring REST Docs)
  
- [x]  애플리케이션 프로파일 설정
  - [x] 개발용 프로파일 설정
  - [x] 프로덕션용 프로파일 설정
  
- [x] 공통 response 생성
- [x] 에러 코드 설정
  - [x] 공통 에러 코드 (CommonErrorCode)
  - [x] 인증 관련 에러 코드 (AuthErrorCode)
  - [x]  데이터베이스 관련 에러 코드 (DatabaseErrorCode)
  - [x]  사용자 관련 에러 코드 (UserErrorCode)
  - [x]  유효성 검사 관련 에러 코드 (ValidationErrorCode)
